[book]
authors = ["Niko Matsakis"]
language = "en"
src = "md"
title = "Dada Formal Model"

[preprocessor.judgment]
command = "cargo run -p mdbook-judgment --"

[output.html]
additional-css = ["judgment.css"]
